# Generated by Django 4.2.14 on 2024-09-28 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageInput",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("image", models.ImageField(upload_to="predictions/")),
            ],
        ),
        migrations.CreateModel(
            name="MachineLearningModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=32, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("algorithm", models.CharField(blank=True, max_length=100, null=True)),
                ("framework", models.CharField(blank=True, max_length=50, null=True)),
                ("feature_names", models.JSONField(blank=True, null=True)),
                ("feature_impacts", models.JSONField(blank=True, null=True)),
                ("feature_maps", models.JSONField(blank=True, null=True)),
                ("output_maps", models.JSONField(blank=True, null=True)),
                ("hyperparameters", models.JSONField(blank=True, null=True)),
                ("model_file_url", models.URLField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("precision", models.FloatField(blank=True, null=True)),
                ("recall", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("input_data", models.JSONField(blank=True, null=True)),
                ("prediction", models.TextField()),
                ("probability", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "image_input",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mlmodels.imageinput",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="mlmodels.machinelearningmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
