# Generated by Django 4.2.14 on 2024-09-28 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mlmodels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prediction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predictions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="machinelearningmodel",
            index=models.Index(
                fields=["name", "version"], name="mlmodels_ma_name_8fb001_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imageinput",
            index=models.Index(
                fields=["created_at"], name="mlmodels_im_created_ecd221_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prediction",
            index=models.Index(
                fields=["user", "created_at"], name="mlmodels_pr_user_id_a4d9f5_idx"
            ),
        ),
    ]
