# Generated by Django 4.2.14 on 2024-08-05 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminpanel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=15, null=True
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("job", models.CharField(blank=True, max_length=50, null=True)),
                ("date_of_birth", models.DateField()),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="services_us_email_e4b658_idx"),
                    models.Index(
                        fields=["phone_number"], name="services_us_phone_n_242668_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FoodScore",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("score", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_scores",
                        to="adminpanel.food",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_scores",
                        to="services.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="services_fo_user_id_10145c_idx"
                    ),
                    models.Index(
                        fields=["food"], name="services_fo_food_id_565db5_idx"
                    ),
                    models.Index(
                        fields=["created"], name="services_fo_created_409f97_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Biometrics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "scaled_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "biochemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometrics",
                        to="adminpanel.biochemical",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometrics",
                        to="services.user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="services_bi_user_id_67dc3c_idx"
                    ),
                    models.Index(
                        fields=["biochemical"], name="services_bi_biochem_c00e8d_idx"
                    ),
                    models.Index(
                        fields=["created"], name="services_bi_created_847a80_idx"
                    ),
                ],
            },
        ),
    ]
