# Generated by Django 4.2.14 on 2024-08-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="biometrics",
            name="health_weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
