# Generated by Django 4.2.14 on 2024-08-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_user_height_cm_alter_user_weight_kg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
