# Generated by Django 4.2.14 on 2024-08-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_user_gender_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
