# Generated by Django 4.2.14 on 2024-08-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="services_user",
        ),
    ]
