# Generated by Django 4.2.14 on 2024-10-17 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminpanel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="symptoms",
                        to="adminpanel.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Precaution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "diseases",
                    models.ManyToManyField(
                        related_name="precautions", to="diagnosis.disease"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "diseases",
                    models.ManyToManyField(
                        related_name="medications", to="diagnosis.disease"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="disease",
            index=models.Index(fields=["name"], name="diagnosis_d_name_61ee3c_idx"),
        ),
        migrations.AddField(
            model_name="diet",
            name="diseases",
            field=models.ManyToManyField(related_name="diets", to="diagnosis.disease"),
        ),
        migrations.AddIndex(
            model_name="symptom",
            index=models.Index(
                fields=["name", "category"], name="diagnosis_s_name_2f7ea5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precaution",
            index=models.Index(fields=["name"], name="diagnosis_p_name_3d2b8d_idx"),
        ),
        migrations.AddIndex(
            model_name="medication",
            index=models.Index(fields=["name"], name="diagnosis_m_name_c03063_idx"),
        ),
        migrations.AddIndex(
            model_name="diet",
            index=models.Index(fields=["name"], name="diagnosis_d_name_aff8e9_idx"),
        ),
    ]
