# Generated by Django 4.2.14 on 2024-08-05 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Biochemical",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("female_min", models.FloatField()),
                ("female_max", models.FloatField()),
                ("male_min", models.FloatField()),
                ("male_max", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("value", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrients",
                        to="adminpanel.category",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrients",
                        to="adminpanel.food",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Weight",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("weight", models.FloatField(db_index=True)),
                (
                    "biochemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="adminpanel.biochemical",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="adminpanel.food",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="adminpanel.nutrient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="adminpanel.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="food",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foods",
                to="adminpanel.subcategory",
            ),
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="adminpanel__name_069433_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="adminpanel__name_0b3e6c_idx"),
        ),
        migrations.AddField(
            model_name="biochemical",
            name="hyper_conditions",
            field=models.ManyToManyField(
                blank=True,
                related_name="hyper_conditions_for_biochemicals",
                to="adminpanel.condition",
            ),
        ),
        migrations.AddField(
            model_name="biochemical",
            name="hypo_conditions",
            field=models.ManyToManyField(
                blank=True,
                related_name="hypo_conditions_for_biochemicals",
                to="adminpanel.condition",
            ),
        ),
        migrations.AddField(
            model_name="biochemical",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biochemicals",
                to="adminpanel.subcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="weight",
            index=models.Index(fields=["weight"], name="adminpanel__weight_38695c_idx"),
        ),
        migrations.AddIndex(
            model_name="weight",
            index=models.Index(
                fields=["nutrient"], name="adminpanel__nutrien_b759c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weight",
            index=models.Index(fields=["food"], name="adminpanel__food_id_30e6ed_idx"),
        ),
        migrations.AddIndex(
            model_name="weight",
            index=models.Index(
                fields=["biochemical"], name="adminpanel__biochem_8cfe81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subcategory",
            index=models.Index(fields=["name"], name="adminpanel__name_67236d_idx"),
        ),
        migrations.AddIndex(
            model_name="subcategory",
            index=models.Index(
                fields=["category"], name="adminpanel__categor_e9887c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nutrient",
            index=models.Index(fields=["name"], name="adminpanel__name_105f89_idx"),
        ),
        migrations.AddIndex(
            model_name="nutrient",
            index=models.Index(
                fields=["category"], name="adminpanel__categor_4af687_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nutrient",
            index=models.Index(fields=["food"], name="adminpanel__food_id_87d658_idx"),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["name"], name="adminpanel__name_2227d1_idx"),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                fields=["subcategory"], name="adminpanel__subcate_34ec61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biochemical",
            index=models.Index(fields=["name"], name="adminpanel__name_5fdc55_idx"),
        ),
        migrations.AddIndex(
            model_name="biochemical",
            index=models.Index(
                fields=["subcategory"], name="adminpanel__subcate_1d6bf3_idx"
            ),
        ),
    ]
