# Generated by Django 4.2.14 on 2024-08-22 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Biochemical",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("female_min", models.FloatField()),
                ("female_max", models.FloatField()),
                ("male_min", models.FloatField()),
                ("male_max", models.FloatField()),
                ("validity_days", models.FloatField()),
                ("unit", models.CharField(default="g/dL", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="BiochemicalCondition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_hyper", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("nutriscore", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("unit", models.CharField(max_length=50)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrients",
                        to="adminpanel.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="adminpanel.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NutrientWeight",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("bias", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "biochemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrient_weights",
                        to="adminpanel.biochemical",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="adminpanel.nutrient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodWeight",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("bias", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "biochemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_weights",
                        to="adminpanel.biochemical",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="adminpanel.food",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodNutrient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("value", models.FloatField()),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrients",
                        to="adminpanel.food",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foods",
                        to="adminpanel.nutrient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="food",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foods",
                to="adminpanel.subcategory",
            ),
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="adminpanel__name_069433_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="adminpanel__name_0b3e6c_idx"),
        ),
        migrations.AddField(
            model_name="biochemicalcondition",
            name="biochemical",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditions",
                to="adminpanel.biochemical",
            ),
        ),
        migrations.AddField(
            model_name="biochemicalcondition",
            name="condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adminpanel.condition"
            ),
        ),
        migrations.AddField(
            model_name="biochemical",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biochemicals",
                to="adminpanel.category",
            ),
        ),
        migrations.AddIndex(
            model_name="subcategory",
            index=models.Index(fields=["name"], name="adminpanel__name_67236d_idx"),
        ),
        migrations.AddIndex(
            model_name="subcategory",
            index=models.Index(
                fields=["category"], name="adminpanel__categor_e9887c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nutrientweight",
            index=models.Index(
                fields=["biochemical", "nutrient", "bias", "weight"],
                name="adminpanel__biochem_64eed1_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nutrientweight",
            unique_together={("biochemical", "nutrient")},
        ),
        migrations.AddIndex(
            model_name="nutrient",
            index=models.Index(fields=["name"], name="adminpanel__name_105f89_idx"),
        ),
        migrations.AddIndex(
            model_name="nutrient",
            index=models.Index(
                fields=["category"], name="adminpanel__categor_4af687_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foodweight",
            index=models.Index(
                fields=["biochemical", "food", "bias", "weight"],
                name="adminpanel__biochem_3cc6b0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="foodweight",
            unique_together={("biochemical", "food")},
        ),
        migrations.AddIndex(
            model_name="foodnutrient",
            index=models.Index(
                fields=["food", "nutrient"], name="adminpanel__food_id_8615c7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="foodnutrient",
            unique_together={("food", "nutrient")},
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(fields=["name"], name="adminpanel__name_2227d1_idx"),
        ),
        migrations.AddIndex(
            model_name="food",
            index=models.Index(
                fields=["subcategory"], name="adminpanel__subcate_34ec61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biochemicalcondition",
            index=models.Index(
                fields=["biochemical", "condition", "is_hyper"],
                name="adminpanel__biochem_e609a9_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="biochemicalcondition",
            unique_together={("biochemical", "condition", "is_hyper")},
        ),
        migrations.AddIndex(
            model_name="biochemical",
            index=models.Index(fields=["name"], name="adminpanel__name_5fdc55_idx"),
        ),
        migrations.AddIndex(
            model_name="biochemical",
            index=models.Index(
                fields=["category"], name="adminpanel__categor_e66ea5_idx"
            ),
        ),
    ]
