# Generated by Django 4.2.14 on 2024-08-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="normalized_nutriscore",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodnutrient",
            name="normalized_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
