# Generated by Django 4.2.14 on 2024-08-06 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0002_biochemical_unit"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="biochemical",
            name="adminpanel__subcate_1d6bf3_idx",
        ),
        migrations.RemoveField(
            model_name="biochemical",
            name="subcategory",
        ),
        migrations.AddField(
            model_name="biochemical",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biochemicals",
                to="adminpanel.category",
            ),
        ),
        migrations.AddIndex(
            model_name="biochemical",
            index=models.Index(
                fields=["category"], name="adminpanel__categor_e66ea5_idx"
            ),
        ),
    ]
