# Generated by Django 4.2.14 on 2024-08-29 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0002_food_normalized_nutriscore_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "food",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="adminpanel.food",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["food"], name="adminpanel__food_id_63830c_idx")
                ],
            },
        ),
    ]
