# Generated by Django 4.2.14 on 2024-08-29 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0003_foodimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FoodImage",
        ),
    ]
