# Generated by Django 4.2.14 on 2024-08-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "adminpanel",
            "0003_remove_biochemical_adminpanel__subcate_1d6bf3_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="adminpanel.category",
            ),
        ),
    ]
