# Generated by Django 4.2.14 on 2024-08-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0005_foodnutrient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrient",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
