# Generated by Django 4.2.14 on 2024-08-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0006_alter_nutrient_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrient",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
