# Generated by Django 4.2.14 on 2024-08-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0008_alter_nutrient_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weight",
            options={"ordering": ["-weight"]},
        ),
        migrations.AlterField(
            model_name="biochemical",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="food",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
