from django.test import TestCase


# {
#   "data": {
#     "Age": 39,
#     "Alanine Aminotransferase": 31.9,
#     "Albumin": 4,
#     "Alkaline Phosphatase": 94.3,
#     "Aspartate Aminotransferase": 30.2,
#     "Bilirubin": 0.8,
#     "Cholinesterase": 45,
#     "Creatinine": 0.83,
#     "Gamma-Glutamyl Transferase": 31.9,
#     "Gender": "female",
#     "Total Cholesterol": 198.3,
#     "Total Protein": 7
#   },
#   "model": "gvghvg56456gfcf"
# }


# {
#   "data": {
#     "Age": 39,
#     "BMI": 22.2,
#     "Blood Urea Nitrogen": 13.8,
#     "Creatinine": 0.83,
#     "Gender": "female",
#     "HDL Cholesterol": 53.7,
#     "Hemoglobin A1c": 5.4,
#     "LDL Cholesterol": 142.4,
#     "Total Cholesterol": 198.3,
#     "Triglycerides": 168.9,
#     "Very Low-Density Lipoprotein": 23
#   },
#   "model": "fgfdsz45667hfzd"
# }



# {
#     "model": "tdsevgg53h5f53e6",
#     "data": {
#         "Abdominal Pain": 0,
#         "Abnormal Menstruation": 0,
#         "Acidity": 0,
#         "Acute Liver Failure": 0,
#         "Altered Sensorium": 0,
#         "Anxiety": 0,
#         "Back Pain": 0,
#         "Belly Pain": 0,
#         "Blackheads": 0,
#         "Bladder Discomfort": 0,
#         "Blister": 0,
#         "Blood in Sputum": 0,
#         "Bloody Stool": 0,
#         "Blurred and Distorted Vision": 0,
#         "Breathlessness": 0,
#         "Brittle Nails": 0,
#         "Bruising": 0,
#         "Burning Micturition": 0,
#         "Chest Pain": 0,
#         "Chills": 0,
#         "Cold Hands and Feet": 0,
#         "Coma": 0,
#         "Congestion": 0,
#         "Constipation": 0,
#         "Continuous Feel of Urine": 0,
#         "Continuous Sneezing": 0,
#         "Cough": 0,
#         "Cramps": 0,
#         "Dark Urine": 0,
#         "Dehydration": 0,
#         "Depression": 0,
#         "Diarrhoea": 0,
#         "Dischromic Patches": 0,
#         "Distention of Abdomen": 0,
#         "Dizziness": 0,
#         "Drying and Tingling Lips": 0,
#         "Enlarged Thyroid": 0,
#         "Excessive Hunger": 0,
#         "Extra Marital Contacts": 0,
#         "Family History": 0,
#         "Fast Heart Rate": 0,
#         "Fatigue": 0,
#         "Fluid Overload": 0,
#         "Foul Smell of Urine": 0,
#         "Gender": "female",
#         "Headache": 0,
#         "High Fever": 0,
#         "Hip Joint Pain": 0,
#         "History of Alcohol Consumption": 0,
#         "Increased Appetite": 0,
#         "Indigestion": 0,
#         "Inflammatory Nails": 0,
#         "Internal Itching": 0,
#         "Irregular Sugar Level": 0,
#         "Irritability": 0,
#         "Irritation in Anus": 0,
#         "Itching": 0,
#         "Joint Pain": 0,
#         "Knee Pain": 0,
#         "Lack of Concentration": 0,
#         "Lethargy": 0,
#         "Loss of Appetite": 0,
#         "Loss of Balance": 0,
#         "Loss of Smell": 0,
#         "Malaise": 0,
#         "Mild Fever": 0,
#         "Mood Swings": 0,
#         "Movement Stiffness": 0,
#         "Mucoid Sputum": 0,
#         "Muscle Pain": 0,
#         "Muscle Wasting": 0,
#         "Muscle Weakness": 0,
#         "Nausea": 0,
#         "Neck Pain": 0,
#         "Nodal Skin Eruptions": 0,
#         "Obesity": 0,
#         "Pain Behind the Eyes": 0,
#         "Pain During Bowel Movements": 0,
#         "Pain in Anal Region": 0,
#         "Painful Walking": 0,
#         "Palpitations": 0,
#         "Passage of Gases": 0,
#         "Patches in Throat": 0,
#         "Phlegm": 0,
#         "Polyuria": 0,
#         "Prominent Veins on Calf": 0,
#         "Puffy Face and Eyes": 0,
#         "Pus Filled Pimples": 0,
#         "Receiving Blood Transfusion": 0,
#         "Receiving Unsterile Injections": 0,
#         "Red Sore Around Nose": 0,
#         "Red Spots Over Body": 1,
#         "Redness of Eyes": 0,
#         "Restlessness": 0,
#         "Runny Nose": 0,
#         "Rusty Sputum": 0,
#         "Scurring": 0,
#         "Shivering": 0,
#         "Silver Like Dusting": 0,
#         "Sinus Pressure": 0,
#         "Skin Peeling": 0,
#         "Skin Rash": 1,
#         "Slurred Speech": 0,
#         "Small Dents in Nails": 0,
#         "Spinning Movements": 0,
#         "Spotting Urination": 0,
#         "Stiff Neck": 0,
#         "Stomach Bleeding": 0,
#         "Stomach Pain": 0,
#         "Sunken Eyes": 0,
#         "Sweating": 0,
#         "Swelled Lymph Nodes": 0,
#         "Swelling Joints": 0,
#         "Swelling of Stomach": 0,
#         "Swollen Blood Vessels": 0,
#         "Swollen Extremities": 0,
#         "Swollen Legs": 0,
#         "Throat Irritation": 0,
#         "Toxic Look (Typhos)": 0,
#         "Ulcers on Tongue": 0,
#         "Unsteadiness": 0,
#         "Visual Disturbances": 0,
#         "Vomiting": 0,
#         "Watering from Eyes": 0,
#         "Weakness in Limbs": 0,
#         "Weakness of One Body Side": 0,
#         "Weight Gain": 0,
#         "Weight Loss": 0,
#         "Yellow Crust Ooze": 0,
#         "Yellow Urine": 0,
#         "Yellowing of Eyes": 0,
#         "Yellowish Skin": 0
#     }
# }
