            
            
            
biochemicals = {
    'Hematology': [
        'Hemoglobin',
        'White Blood Cell Count',
        'Platelet Count',
        'Erythropoietin',
    ]
    'Biochemistry': [
        'Glucose',
        'Calcium',
        'Sodium',
        'Potassium',
        'Chloride',
        'Blood Urea Nitrogen',
        'Creatinine',
        'Albumin',
        'Total Protein',
        'Alkaline Phosphatase',
        'ALT',
        'AST',
        'Total Bilirubin',
        'Direct Bilirubin',
        'Total Cholesterol',
        'HDL Cholesterol',
        'LDL Cholesterol',
        'Triglycerides',
        'Uric Acid',
        'Lactate Dehydrogenase',
        'Amylase',
        'Lipase',
    ]
    'Endocrine': [
        'TSH',
        'Free T4',
        'Free T3',
        'HbA1c',
        'Fasting Blood Glucose',
        'OGTT',
        'Estrogen',
        'Progesterone',
        'Testosterone',
        'Cortisol',
        'Prolactin',
        'Vitamin D',
        'Vitamin B12',
        'Folate',
        'Insulin',
        'Parathyroid Hormone',
        'Adrenocorticotropic Hormone (ACTH)',
        'Growth Hormone',
        'Thyroid Peroxidase Antibodies',
        'Thyroglobulin Antibodies',
    ]
    'Electrolytes': [
        'Sodium',
        'Potassium',
        'Chloride',
        'Glomerular Filtration Rate',
        'Bicarbonate',
        'Magnesium',
        'Calcium',
        'Phosphate',
    ]
    'Cardiac': [
        'Troponin',
        'CK-MB',
        'BNP',
        'Myoglobin',
        'Homocysteine',
    ]
    'Liver': [
        'ALT',
        'AST',
        'Alkaline Phosphatase',
        'Total Bilirubin',
        'Direct Bilirubin',
        'Gamma-Glutamyl Transferase (GGT)',
        'Prothrombin Time',
        'Albumin',
    ]
    'Inflammatory': [
        'CRP',
        'ESR',
        'Procalcitonin',
        'Interleukin-6',
        'Tumor Necrosis Factor Alpha',
        'Ferritin',
    ]
    'Coagulation': [
        'Prothrombin Time',
        'INR',
        'APTT',
        'D-Dimer',
        'Fibrinogen',
        'Platelet Function Assay',
    ]
    'Nutritional': [
        'Iron',
        'Ferritin',
        'TIBC',
        'Transferrin Saturation',
        'Magnesium',
        'Zinc',
        'Copper',
        'Manganese',
        'Phosphorus',
        'Selenium',
        'Iodine',
        'Molybdenum',
        'Boron',
        'Chromium',
        'Cobalt',
        'Nickel',
        'Silicon',
        'Vanadium',
        'Vitamin A',
        'Vitamin E',
        'Vitamin K',
        'Vitamin C',
        'Vitamin B1',
        'Vitamin B2',
        'Vitamin B3',
        'Vitamin B5',
        'Vitamin B6',
        'Vitamin B7',
        'Vitamin B9',
        'Vitamin B12',
        'Omega-3 Fatty Acids',
        'Omega-6 Fatty Acids',
    ]
    'Neurotransmitters': [
        'Oxytocin',
        'Melatonin',
        'Histamine',
        'Serotonin',
        'Dopamine',
        'Norepinephrine',
        'Epinephrine',
        'Acetylcholine',
        'GABA',
        'Glutamate',
        'Aspartate',
        'Glycine',
    ]
    'Amino Acids and Coenzymes': [
        'Arginine',
        'Carnitine',
        'Coenzyme Q10',
        'Glutathione',
        'Inositol',
        'Taurine',
        'Choline',
        'Cysteine',
        'Methionine',
        'Lysine',
        'Histidine',
        'Leucine',
        'Isoleucine',
        'Valine',
        'Phenylalanine',
        'Tyrosine',
        'Tryptophan',
        'Alanine',
        'Asparagine',
        'Glutamine',
        'Proline',
        'Serine',
        'Threonine',
    ]
    'Urine': [
        'pH',
        'Protein',
        'Glucose',
        'Ketones',
        'Blood',
        'Leukocytes',
        'Nitrites',
        'Urobilinogen',
        'Bilirubin',
        'Specific Gravity',
        'Microalbumin',
    ]
    'Lipids': [
        'Total Cholesterol',
        'HDL Cholesterol',
        'LDL Cholesterol',
        'Triglycerides',
        'VLDL Cholesterol',
        'Apolipoprotein A1',
        'Apolipoprotein B',
        'Lipoprotein (a)',
    ]
    'Metabolites': [
        'Lactic Acid',
        'Pyruvate',
        'Ammonia',
        'Bilirubin',
        'Bile Acids',
        'Urea',
        'Creatine',
        'Uric Acid',
        'Glycated Albumin',
    ]
    'Hormones': [
        'Insulin',
        'Glucagon',
        'Cortisol',
        'Adrenaline',
        'Noradrenaline',
        'Growth Hormone',
        'Prolactin',
        'Estrogen',
        'Progesterone',
        'Testosterone',
        'Aldosterone',
        'Antidiuretic Hormone',
        'Thyroxine (T4)',
        'Triiodothyronine (T3)',
        'Parathyroid Hormone',
    ]
    'Immune Markers': [
        'Immunoglobulin A (IgA)',
        'Immunoglobulin G (IgG)',
        'Immunoglobulin M (IgM)',
        'Immunoglobulin E (IgE)',
        'Immunoglobulin D (IgD)',
        'C3 Complement',
        'C4 Complement',
        'Antinuclear Antibodies (ANA)',
        'Rheumatoid Factor',
    ]
    'Tumor Markers': [
        'Prostate-Specific Antigen (PSA)',
        'CA-125',
        'CA 19-9',
        'Carcinoembryonic Antigen (CEA)',
        'Alpha-Fetoprotein (AFP)',
        'Human Chorionic Gonadotropin (hCG)',
    ]
}

